logging:
  version: 1
  formatters:
    formatter:
      format: '{"@timestamp": "%(asctime)s", "log.level": "%(levelname)s", "message": "%(message)s"}'
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "DEBUG"
      formatter: "formatter"
      stream: "ext://sys.stdout"
  root:
    level: "DEBUG"
    handlers: [ "console" ]

input_file_path: "./test_data/Input_json_file.json"
employees_over_30_output_path: "./test_data/employees_over_30_json_path.json"

mongodb:
    connection_string: "mongodb+srv://mongo:mongo@employees.vkvskkk.mongodb.net/"
    db_name: "employees"